import { v4 as uuidv4 } from 'uuid'

export const AllComunityBD = [
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/uniteGaming.png',
		// subGenre: 'next',
		title: 'titleNews',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/chat.png',
		// subGenre: 'next',
		title: 'titleChat',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/helps.png',
		// subGenre: 'next',
		title: 'titleHelps',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/timate.png',
		// subGenre: 'next',
		title: 'titleTeams',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/sesGame.png',
		// subGenre: 'next',
		title: 'titleSes',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/GTA.png',
		// subGenre: 'next',
		title: 'titleGta',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/rust.png',
		// subGenre: 'next',
		title: 'titleRust',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/csgo.png',
		// subGenre: 'next',
		title: 'titleCsGo',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/cs1.6.png',
		// subGenre: 'next',
		title: 'titleCs',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/mobileGame.png',
		// subGenre: 'next',
		title: 'titleMobGame',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/dota.png',
		// subGenre: 'next',
		title: 'titleDota',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/garrys.png',
		// subGenre: 'next',
		title: 'titleGarrys',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/world.png',
		// subGenre: 'next',
		title: 'titleWorld',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/mine.png',
		// subGenre: 'next',
		title: 'titleMine',
		downloadLink: '',
		item: '',
		data: 'next',
	},
	{
		id: uuidv4(),
		imgCard: '/public/AllComunity/PicturesCards/samp.png',
		// subGenre: 'next',
		title: 'titleSamp',
		downloadLink: '',
		item: '',
		data: 'next',
	},
]
