import { v4 as uuidv4 } from 'uuid'

export const OnlineGamesBD = [
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/factorio.jpg',
		imgCard: '/OnlineGamesPictures/PicturesCard/factorioCard.png',
		subGenre: 'subGenre',
		title: 'Factorio',
		downloadLink: 'https://www.factorio.com/buy',
		instruction: 'https://wiki.factorio.com/',
		players: `1 - 255`,
		item: 'items1',
		descriptionKey: 'subtitle',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/J8SBp4SyvLc?si=HlLBb1TXqHv9rpCW',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/terraria.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/terrariaCard.jpg',
		subGenre: 'subGenre1',
		title: 'Terraria',
		downloadLink: 'https://store.steampowered.com/app/105600/Terraria/',
		instruction: 'https://terraria.wiki.gg/wiki/Terraria_Wiki',
		players: `1 - 8`,
		item: 'items2',
		descriptionKey: 'subtitle1',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/w7uOhFTrrq0?si=2nfpqtJx4QhkjhUX',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/forest.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/forestCard.jpg',
		subGenre: 'subGenre2',
		title: 'The Forest',
		downloadLink: 'https://store.steampowered.com/app/242760/The_Forest/',
		instruction: 'https://the-forest.fandom.com/wiki/The_Forest_Wiki',
		players: `1 - 8`,
		item: 'items3',
		descriptionKey: 'subtitle2',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/7mwn5U2PNvk?si=ashzCOZjRKQt0gDE',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/left.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/left4Card.jpg',
		title: 'Left4Dead 2',
		subGenre: 'subGenre3',
		downloadLink:
			'https://store.steampowered.com/app/550/Left_4_Dead_2/?l=russian',
		instruction: 'https://left4dead.fandom.com/ru/wiki/Left_4_Dead_2',
		players: `1 - 8`,
		item: 'items4',
		descriptionKey: 'subtitle3',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/N1shYxPdGB8?si=vZqcPeXLeUOHQ_9e',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/bigfoot.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/bigfootCard.jpg',
		title: 'Bigfoot',
		subGenre: 'subGenre4',
		downloadLink:
			'https://store.steampowered.com/app/509980/BIGFOOT/?l=ukrainian',
		instruction: 'https://bigfootgame.fandom.com/wiki/Bigfoot',
		players: `1 - 8`,
		item: 'items5',
		descriptionKey: 'subtitle4',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/AENrQm1Bw_g?si=Eru-JUJMfVTjuPCz',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/portal.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/portalCard.jpg',
		title: 'Portal 2',
		subGenre: 'subGenre5',
		downloadLink: 'https://store.steampowered.com/app/620/Portal_2/?',
		instruction: 'https://theportalwiki.com/wiki/Main_Page/ru',
		players: `1 - 8`,
		item: 'items6',
		descriptionKey: 'subtitle5',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/A88YiZdXugA?si=JFevqwRm9tCpMxfi',
	},
	{
		id: uuidv4(),
		img: '/public/ServicesGames/Pictures/csgo.png',
		imgCard: '/public/ServicesGames/picturesCard/CSGO.png',
		title: 'CS:GO',
		subGenre: 'subGenre6',
		downloadLink: 'https://store.steampowered.com/app/730/CounterStrike_2/',
		instruction:
			'https://steamcommunity.com/sharedfiles/filedetails/?id=584294992',
		players: `1 - 8`,
		item: 'items7',
		descriptionKey: 'subtitle6',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/edYCtaNueQY?si=XyWlsQ3iVwuNwzD6',
	},
	{
		id: uuidv4(),
		img: '/public/ServicesGames/Pictures/css.png',
		imgCard: '/public/ServicesGames/picturesCard/CSS.png',
		title: 'CS:Source',
		subGenre: 'subGenre7',
		downloadLink:
			'https://store.steampowered.com/app/240/CounterStrike_Source/',
		instruction:
			'https://steamcommunity.com/sharedfiles/filedetails/?id=186483458',
		players: `1 - 8`,
		item: 'items8',
		descriptionKey: 'subtitle7',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/bvI62FUDpKA?si=L2az_XTnJ0SG3riq',
	},
	{
		id: uuidv4(),
		img: '/public/ServicesGames/Pictures/cs16.jpg',
		imgCard: '/public/ServicesGames/picturesCard/CS16.png',
		title: 'CS:1.6',
		subGenre: 'subGenre8',
		downloadLink:
			'https://store.steampowered.com/app/10/CounterStrike/?l=russian',
		instruction:
			'https://steamcommunity.com/sharedfiles/filedetails/?id=186125396',
		players: `1 - 8`,
		item: 'items9',
		descriptionKey: 'subtitle8',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/j71GvZ26H6c?si=m_TihE4cW-h4Rbj3',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/dontStarve.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/dontStarveCard.jpg',
		title: 'Don’t Starve Together',
		subGenre: 'subGenre9',
		downloadLink:
			'https://store.steampowered.com/app/322330/Dont_Starve_Together/',
		instruction:
			'https://dont-starve.fandom.com/ru/wiki/Don%27t_Starve_Together',
		players: `1 - 8`,
		item: 'items10',
		descriptionKey: 'subtitle9',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/bVbyn7c1X6E?si=eGerNAlOVhmYmEnm',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/Generals.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/generalsCard.jpg',
		title: 'Generals',
		subGenre: 'subGenre10',
		downloadLink:
			'https://store.steampowered.com/app/2229870/Command__Conquer_Generals/?l=russian',
		instruction: 'https://cnc.fandom.com/ru/wiki/C%26C:_Generals',
		players: `1 - 8`,
		item: 'items11',
		descriptionKey: 'subtitle10',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/j1BZtg8OyIo?si=meYvc4QsTS3BCtse',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/rainbow.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/rainbowSixCard.jpg',
		title: 'Rainbow Six Siege',
		subGenre: 'subGenre11',
		downloadLink:
			'https://store.steampowered.com/app/359550/Tom_Clancys_Rainbow_Six_Siege/',
		instruction: 'https://rainbowsix.fandom.com/wiki/Rainbow_Six_Wiki',
		players: `1 - 8`,
		item: 'items12',
		descriptionKey: 'subtitle11',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/hLjEHanGIuI?si=dkkIgsbnuK5buadm',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/warcrawt3.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/warcrawt3Card.jpg',
		title: 'Warcraft 3',
		subGenre: 'subGenre12',
		downloadLink: 'https://warcraft3.blizzard.com/ru-ru/',
		instruction: 'https://eu.forums.blizzard.com/ru/warcraft3/',
		players: `1 - 8`,
		item: 'items13',
		descriptionKey: 'subtitle12',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/72UbFQO5-m0?si=-k48dLeBZsMBevE_',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/7Days.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/7DaysCard.jpg',
		title: '7 Days to Die',
		subGenre: 'subGenre13',
		downloadLink: 'https://store.steampowered.com/app/251570/7_Days_to_Die/',
		instruction:
			'https://7daystodie.fandom.com/ru/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F',
		players: `1 - 8`,
		item: 'items14',
		descriptionKey: 'subtitle13',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/kikTJaVBank?si=qgqAg0LhGvpr3mZy',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/tournament.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/tournamentCard.jpg',
		title: 'Unreal Tournament 3',
		subGenre: 'subGenre14',
		downloadLink:
			'https://store.steampowered.com/app/13210/Unreal_Tournament_3/?',
		instruction: 'https://unreal.fandom.com/wiki/Unreal_Tournament_3',
		players: `1 - 8`,
		item: 'items15',
		descriptionKey: 'subtitle14',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/JUCMqEI9AWg?si=dlbrRr8W0xuTqOLC',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/CoD4.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/CoD4Card.jpg',
		title: 'Call of Duty 4',
		subGenre: 'subGenre14',
		downloadLink:
			'https://store.steampowered.com/app/7940/Call_of_Duty_4_Modern_Warfare_2007/?l=russian',
		instruction:
			'https://callofduty.fandom.com/ru/wiki/Call_of_Duty_4:_Modern_Warfare',
		players: `1 - 8`,
		item: 'items16',
		descriptionKey: 'subtitle15',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/LhuIjNSg7Gg?si=yvO6fca04y4QDCgs',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/CoD5.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/CoD5Card.jpg',
		title: 'Call of Duty 5',
		subGenre: 'subGenre16',
		downloadLink:
			'https://store.steampowered.com/app/10090/Call_of_Duty_World_at_War/?l=ukrainian',
		instruction:
			'https://callofduty.fandom.com/ru/wiki/Call_of_Duty:_World_at_War',
		players: `1 - 8`,
		item: 'items17',
		descriptionKey: 'subtitle16',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/D4Q_XYVescc?si=VudMFJs2uS0tELGj',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/CoD6.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/CoD6Card.jpg',
		title: 'Call of Duty 6',
		subGenre: 'subGenre17',
		downloadLink:
			'https://store.steampowered.com/app/2933620/Call_of_Duty_Black_Ops_6/?l=ukrainian',
		instruction:
			'https://callofduty.fandom.com/ru/wiki/Call_of_Duty:_Black_Ops_6',
		players: `1 - 8`,
		item: 'items18',
		descriptionKey: 'subtitle17',
		sistemReq: '',
		feedback: '6/10',
		videos: 'https://www.youtube.com/embed/h0uxvKUjsj4?si=jT1056H1WkRtN_d0',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/blur.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/blurCard.jpg',
		title: 'Blur',
		subGenre: 'subGenre18',
		downloadLink: 'https://www.myabandonware.com/game/blur-gls',
		instruction: 'https://blur.fandom.com/wiki/Blur_Wiki',
		players: `1 - 8`,
		item: 'items19',
		descriptionKey: 'subtitle18',
		sistemReq: '',
		feedback: '8/10',
		videos: 'https://www.youtube.com/embed/YKy8CIedSM4?si=Tu5uDRGBb_230bDN',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/cleanUp.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/cleanupCard.jpg',
		title: 'Viscera Cleanup Detail',
		subGenre: 'subGenre19',
		downloadLink:
			'https://store.steampowered.com/app/246900/Viscera_Cleanup_Detail/',
		instruction:
			'https://viscera-cleanup-detail.fandom.com/wiki/Viscera_Cleanup_Detail_Wiki',
		players: `1 - 8`,
		item: 'items20',
		descriptionKey: 'subtitle19',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/90U9xHRRCK0?si=C_CWPnw0mIS39yqj',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/borderlands.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/borderlandsCard.jpg',
		title: 'Borderlands 2',
		subGenre: 'subGenre20',
		downloadLink: 'https://store.steampowered.com/app/49520/Borderlands_2/',
		instruction: 'https://borderlands.fandom.com/ru/wiki/Borderlands_2',
		players: `1 - 8`,
		item: 'items21',
		descriptionKey: 'subtitle20',
		sistemReq: '',
		feedback: '10/10',
		videos: 'https://www.youtube.com/embed/kKVf5feSMEg?si=Td6T9H8bW39fDPGu',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/NFS.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/NFSCard.jpg',
		title: 'NFS:Underground',
		subGenre: 'subGenre21',
		downloadLink:
			'https://oldgamesdownload.com/need-for-speed-underground-xb3/',
		instruction:
			'https://needforspeed.fandom.com/ru/wiki/Need_for_Speed:_Underground',
		players: `1 - 8`,
		item: 'items22',
		descriptionKey: 'subtitle21',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/Ahl_QwuABEU?si=a02zFAkSm_KnB_Ro',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/civil.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/CivilCard.jpg',
		title: 'Civilization 6',
		subGenre: 'subGenre22',
		downloadLink:
			'https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/',
		instruction: 'https://civilization.fandom.com/wiki/Civilization_VI',
		players: `1 - 8`,
		item: 'items23',
		descriptionKey: 'subtitle22',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/c1bfgARmuGQ?si=R86RIDrIjbt_gJxD',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/sniperGhost.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/SniperGhostCard.jpg',
		title: 'Sniper Ghost Warrior 2',
		subGenre: 'subGenre23',
		downloadLink:
			'https://store.steampowered.com/app/34870/Sniper_Ghost_Warrior_2/?l=russian',
		instruction:
			'https://sniperghostwarrior.fandom.com/wiki/Sniper:_Ghost_Warrior_2',
		players: `1 - 8`,
		item: 'items24',
		descriptionKey: 'subtitle23',
		sistemReq: '',
		feedback: '7/10',
		videos: 'https://www.youtube.com/embed/MrionZpp0aE?si=EHxkRTiJ-Ade_azo',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/GTFO.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/GTFOCard.jpg',
		title: 'GTFO',
		subGenre: 'subGenre24',
		downloadLink: 'https://store.steampowered.com/app/493520/GTFO/',
		instruction: 'https://gtfo.fandom.com/wiki/GTFO_Wiki',
		players: `1 - 8`,
		item: 'items25',
		descriptionKey: 'subtitle24',
		sistemReq: '',
		feedback: '8/10',
		videos: 'https://www.youtube.com/embed/NAMw22hSLl4?si=OZlG3LaFoe4ROJuA',
	},
	{
		id: uuidv4(),
		img: '/OnlineGamesPictures/Pictures/amongUs.png',
		imgCard: '/OnlineGamesPictures/PicturesCard/AmongUsCard.jpg',
		title: 'Among Us',
		subGenre: 'subGenre25',
		downloadLink:
			'https://store.steampowered.com/app/945360/Among_Us/?l=ukrainian',
		instruction: 'https://among-us.fandom.com/wiki/Among_Us_Wiki',
		players: `1 - 8`,
		item: 'items26',
		descriptionKey: 'subtitle25',
		sistemReq: '',
		feedback: '9/10',
		videos: 'https://www.youtube.com/embed/CermGp8bwFE?si=1hXMegviOXxhdc4b',
	},
	// {
	// 	id: uuidv4(),
	// 	img: '',
	// 	imgCard: '',
	// 	title: '',
	// subGenre: 'subGenre26',
	// 	downloadLink: '',
	// 	instruction: '',
	// 	players: `1 - 8`,
	// 	item: 'items27',
	// 	descriptionKey: 'subtitle26',
	// 	sistemReq: '',
	// 	feedback: '9/10',
	// 	videos: '',
	// },
]
