import { v4 as uuidv4 } from 'uuid'

const BASE_PATH = `/United`;

export const servicesGamesCards = [
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/rustServPreview.png`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/rustServ.png`,
		subGenre: `Survival, PVP/PVE`,
		title: `RUST`,
		downloadLink: `https://store.steampowered.com/app/252490/Rust/`,
		instruction: `https://www.rust-lang.org/learn`,
		players: `players1`,
		item: `item1`,
		descriptionKey: `description`,
		sistemReq: ``,
		feedback: `9/10`,
		videos: `https://www.youtube.com/embed/-YhCvGVop1Q?si=Eod5v2Aky6iSW2oO`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/mine.jpg`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/Minecraft.png`,
		subGenre: `Sandbox, survival`,
		title: `Minecraft`,
		downloadLink: `https://www.minecraft.net/en-us/download`,
		instruction: `https://www.minecraft.net/en-us/article/how-minecraft`,
		players: `players2`,
		item: `item2`,
		descriptionKey: `description2`,
		sistemReq: ``,
		feedback: `9.5/10`,
		videos: `https://www.youtube.com/embed/MmB9b5njVbA?si=lzIdmlfcWtQJCikO`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/samp.png`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/SAMP.png`,
		subGenre: `Action-adventure`,
		title: `SAMP`,
		downloadLink: `https://www.sa-mp.mp/`,
		instruction:
			`https://steamcommunity.com/sharedfiles/filedetails/?id=2839134094`,
		players: `players3`,
		item: `item3`,
		descriptionKey: `description3`,
		sistemReq: ``,
		feedback: `9.5/10`,
		videos: `https://www.youtube.com/embed/35vmy2Z2s94?si=6ZbfYG0wrl4sAVVp`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/wow.jpg`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/wow.png`,
		subGenre: `Action-adventure`,
		title: `World of Warcraft: Mists of Pandaria`,
		downloadLink: `https://pandawow.me/`,
		instruction:
			`https://forum.pandawow.me/topic/37827-how-to-start-play-instructions/`,
		players: `players4`,
		item: `item4`,
		descriptionKey: `description4`,
		sistemReq: ``,
		feedback: `6.5/10`,
		videos: `https://www.youtube.com/embed/wvYXoyxLv64?si=xLhYWZB7psL3piVd`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/1_B-cUO1UL5znu_5C4anuFIA.jpg`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/world-of-warcraft.png`,
		subGenre: `Action-adventure`,
		title: `WoW: Wrath of the Lich King`,
		downloadLink:
			`https://uwow.biz/6-skachat-klienta-dlya-world-of-warcraft.html`,
		instruction: `https://www.wowhead.com/guide=wotlk`,
		players: `players5`,
		item: `item5`,
		descriptionKey: `description5`,
		sistemReq: ``,
		feedback: `6.5/10`,
		videos: `https://www.youtube.com/embed/L3Mg6lk6yyA?si=0cg1Y0u08sL0pNT7`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/garrysmod.jpg`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/Garys.png`,
		subGenre: `first person shooter, sandbox`,
		title: `Garry’s Mod`,
		downloadLink: `https://store.steampowered.com/app/4000/Garrys_Mod/`,
		instruction:
			`https://steamcommunity.com/sharedfiles/filedetails/?id=2781804290`,
		players: `players6`,
		item: `item6`,
		descriptionKey: `description6`,
		sistemReq: ``,
		feedback: `10/10`,
		videos: `https://www.youtube.com/embed/BRZsBBbnMWw?si=yF3jH_91nMELOYcX`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/csgo.png`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/CSGO.png`,
		subGenre: `Shooter`,
		title: `CS:GO`,
		downloadLink: `https://store.steampowered.com/app/730/CounterStrike_2/`,
		instruction:
			`https://steamcommunity.com/sharedfiles/filedetails/?id=584294992`,
		players: `players7`,
		item: `item7`,
		descriptionKey: `description7`,
		sistemReq: ``,
		feedback: `9/10`,
		videos: `https://www.youtube.com/embed/edYCtaNueQY?si=XyWlsQ3iVwuNwzD6`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/css.jpg`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/CSS.png`,
		subGenre: `Shooter`,
		title: `CS:Source`,
		downloadLink:
			`https://store.steampowered.com/app/240/CounterStrike_Source/`,
		instruction:
			`https://steamcommunity.com/sharedfiles/filedetails/?id=186483458`,
		players: `players8`,
		item: `item8`,
		descriptionKey: `description8`,
		sistemReq: ``,
		feedback: `10/10`,
		videos: `https://www.youtube.com/embed/bvI62FUDpKA?si=L2az_XTnJ0SG3riq`,
	},
	{
		id: uuidv4(),
		img: `${BASE_PATH}/ServicesGames/Pictures/cs16.jpg`,
		imgCard: `${BASE_PATH}/ServicesGames/picturesCard/CS16.png`,
		subGenre: `Shooter`,
		title: `CS:1.6`,
		downloadLink:
			`https://store.steampowered.com/app/10/CounterStrike/?l=russian`,
		instruction:
			`https://steamcommunity.com/sharedfiles/filedetails/?id=186125396`,
		players: `players9`,
		item: `item9`,
		descriptionKey: `description9`,
		sistemReq: ``,
		feedback: `10/10`,
		videos: `https://www.youtube.com/embed/j71GvZ26H6c?si=m_TihE4cW-h4Rbj3`,
	},
]
