import { v4 as uuidv4 } from 'uuid'

export const NewsBD = [
	{
		id: uuidv4(),
		img: '/ServicesGames/Pictures/mine.jpg',
		imgCard: '/NewsPictures/PicturesCard/minecraft.jpg',
		subGenre: 'newsInnerListSubM',
		data: 'newsInnerListFooterTime',
		title: 'newsInnerListTitleM',
		item: 'itemMine',
		descriptionKey: 'description001',
		descriptionKey2: 'description002',
		descriptionKey3: 'description003',
		descriptionKey4: 'description004',
		descriptionKey5: 'description005',
		descriptionKey6: 'description006',
		descriptionKey7: 'description007',
		descriptionKey8: 'description008',
		descriptionKey9: 'description009',
		descriptionKey10: 'description010',
		descriptionKey11: 'description011',
		descriptionKey12: 'description012',
		descriptionKey13: 'description013',
		descriptionKey14: 'description014',
		descriptionKey15: 'description015',
		descriptionKey16: 'description016',
		descriptionKey17: 'description017',
		descriptionKey18: 'description018',
		descriptionKey19: 'description019',
		descriptionKey20: 'description020',
		descriptionKey21: 'description021',
		descriptionKey22: 'description022',
		descriptionKey23: 'description023',
		descriptionKey24: 'description024',
		descriptionKey25: 'description025',
		descriptionKey26: 'description026',
		descriptionKey27: 'description027',
		descriptionKey28: 'description028',
	},
]