import { v4 as uuidv4 } from 'uuid'

const BASE_PATH = `/United`;

export const GameTekBD = [
	{
		id: uuidv4(),
		title: `titleNY`,
		gpsName: `gpsNYName`,
		telName: `telNYName`,
		todoName: `todoNYName`,
		gpsLogo: `${BASE_PATH}/ParnersProduct/logo/gps.png`,
		telLogo: `${BASE_PATH}/ParnersProduct/logo/tel.png`,
		todoLogo: `${BASE_PATH}/ParnersProduct/logo/todo.png`,
		logo: `${BASE_PATH}/ParnersProduct/logo/logoTek.png`,
	},
	{
		id: uuidv4(),
		title: `titleCyber`,
		gpsName: `gpsCyberName`,
		telName: `telCyberName`,
		todoName: `todoCyberName`,
		gpsLogo: `${BASE_PATH}/ParnersProduct/logo/gps.png`,
		telLogo: `${BASE_PATH}/ParnersProduct/logo/tel.png`,
		todoLogo: `${BASE_PATH}/ParnersProduct/logo/todo.png`,
		logo: `${BASE_PATH}/ParnersProduct/logo/logoTek.png`,
	},
	{
		id: uuidv4(),
		title: `titleCyber`,
		gpsName: `gpsCyber2Name`,
		telName: `telCyber2Name`,
		todoName: `todoCyber2Name`,
		gpsLogo: `${BASE_PATH}/ParnersProduct/logo/gps.png`,
		telLogo: `${BASE_PATH}/ParnersProduct/logo/tel.png`,
		todoLogo: `${BASE_PATH}/ParnersProduct/logo/todo.png`,
		logo: `${BASE_PATH}/ParnersProduct/logo/logoTek.png`,
	},
	{
		id: uuidv4(),
		title: `titleMir`,
		gpsName: `gpsMirName`,
		telName: `telMirName`,
		todoName: `todoMirName`,
		gpsLogo: `${BASE_PATH}/ParnersProduct/logo/gps.png`,
		telLogo: `${BASE_PATH}/ParnersProduct/logo/tel.png`,
		todoLogo: `${BASE_PATH}/ParnersProduct/logo/todo.png`,
		logo: `${BASE_PATH}/ParnersProduct/logo/logoTek.png`,
	},
	{
		id: uuidv4(),
		title: `titleHowdan`,
		gpsName: `gpsHowdanName`,
		telName: `telHowdanName`,
		todoName: `todoHowdanName`,
		gpsLogo: `${BASE_PATH}/ParnersProduct/logo/gps.png`,
		telLogo: `${BASE_PATH}/ParnersProduct/logo/tel.png`,
		todoLogo: `${BASE_PATH}/ParnersProduct/logo/todo.png`,
		logo: `${BASE_PATH}/ParnersProduct/logo/logoTek.png`,
	},
]