import { v4 as uuidv4 } from 'uuid'

export const GameTekBD = [
	{
		id: uuidv4(),
		title: 'titleNY',
		gpsName: 'gpsNYName',
		telName: 'telNYName',
		todoName: 'todoNYName',
		gpsLogo: '/public/ParnersProduct/logo/gps.png',
		telLogo: '/public/ParnersProduct/logo/tel.png',
		todoLogo: '/public/ParnersProduct/logo/todo.png',
		logo: '/public/ParnersProduct/logo/logoTek.png',
	},
	{
		id: uuidv4(),
		title: 'titleCyber',
		gpsName: 'gpsCyberName',
		telName: 'telCyberName',
		todoName: 'todoCyberName',
		gpsLogo: '/public/ParnersProduct/logo/gps.png',
		telLogo: '/public/ParnersProduct/logo/tel.png',
		todoLogo: '/public/ParnersProduct/logo/todo.png',
		logo: '/public/ParnersProduct/logo/logoTek.png',
	},
	{
		id: uuidv4(),
		title: 'titleCyber',
		gpsName: 'gpsCyber2Name',
		telName: 'telCyber2Name',
		todoName: 'todoCyber2Name',
		gpsLogo: '/public/ParnersProduct/logo/gps.png',
		telLogo: '/public/ParnersProduct/logo/tel.png',
		todoLogo: '/public/ParnersProduct/logo/todo.png',
		logo: '/public/ParnersProduct/logo/logoTek.png',
	},
	{
		id: uuidv4(),
		title: 'titleMir',
		gpsName: 'gpsMirName',
		telName: 'telMirName',
		todoName: 'todoMirName',
		gpsLogo: '/public/ParnersProduct/logo/gps.png',
		telLogo: '/public/ParnersProduct/logo/tel.png',
		todoLogo: '/public/ParnersProduct/logo/todo.png',
		logo: '/public/ParnersProduct/logo/logoTek.png',
	},
	{
		id: uuidv4(),
		title: 'titleHowdan',
		gpsName: 'gpsHowdanName',
		telName: 'telHowdanName',
		todoName: 'todoHowdanName',
		gpsLogo: '/public/ParnersProduct/logo/gps.png',
		telLogo: '/public/ParnersProduct/logo/tel.png',
		todoLogo: '/public/ParnersProduct/logo/todo.png',
		logo: '/public/ParnersProduct/logo/logoTek.png',
	},
]