import { v4 as uuidv4 } from 'uuid'

export const GamesForAndroid = [
	{
		id: uuidv4(),
		img: '/public/GamesForAndoid/Pictures/mine.png',
		imgCard: '/public/GamesForAndoid/PicturesCard/maine.png',
		subGenre: 'Open World, Sandbox',
		title: 'Minecraft: PE',
		downloadLink:
			'https://play.google.com/store/apps/details?id=com.mojang.minecraftpe&hl=ru',
		instruction: 'https://minecraft.fandom.com/ru/wiki/Pocket_Edition',
		players: `1 - 10`,
		item: 'itemsMine',
		descriptionKey: 'subtitleMine',
		sistemReq: '',
		feedback: '9.0',
		videos: 'https://www.youtube.com/embed/X-fMtNOS_gU?si=TTblTr111_nciBo7',
	},
	{
		id: uuidv4(),
		img: '/public/GamesForAndoid/Pictures/samp.png',
		imgCard: '/public/GamesForAndoid/PicturesCard/samp.png',
		subGenre: 'RP, Simulation, Action',
		title: 'SAMP Mobile',
		downloadLink: 'https://samp-mobile.com/samp-mobile.apk',
		instruction:
			'https://pawn.wiki/index.php?/topic/49423-samp-mobile-android-sbornik-urokov/',
		players: `1 - 1000`,
		item: 'itemsSampM',
		descriptionKey: 'subtitleSampM',
		sistemReq: '',
		feedback: '8.2',
		videos: 'https://www.youtube.com/embed/QLcXGBq8_Og?si=xzD6n9J3YW7EzDtD',
	},
	{
		id: uuidv4(),
		img: '/public/GamesForAndoid/Pictures/los.png',
		imgCard: '/public/GamesForAndoid/PicturesCard/los.png',
		subGenre: 'Action, Racing, Open World',
		title: 'Los Angeles Crime',
		downloadLink: 'https://play.google.com/store/apps/details?id=com.MA.LAC',
		instruction:
			'https://truecrime.fandom.com/wiki/Random_Crimes_in_Los_Angeles',
		players: `1 - 10`,
		item: 'itemsLos',
		descriptionKey: 'subtitleLos',
		sistemReq: '',
		feedback: '8.6',
		videos: 'https://www.youtube.com/embed/G4N-wAIW0VE?si=rcGs7yqZsIwlkava',
	},
	{
		id: uuidv4(),
		img: '/public/GamesForAndoid/Pictures/sf.png',
		imgCard: '/public/GamesForAndoid/PicturesCard/sf.png',
		subGenre: 'Shooters, Action',
		title: 'Special Forces Group 2',
		downloadLink:
			'https://play.google.com/store/apps/details?id=com.ForgeGames.SpecialForcesGroup2&hl=uk',
		instruction:
			'https://special-forces-group.fandom.com/wiki/Special_Forces_Group_2',
		players: `1 - 16`,
		item: 'itemsSF',
		descriptionKey: 'subtitleSF',
		sistemReq: '',
		feedback: '8.8',
		videos: 'https://www.youtube.com/embed/e-ATGMV9ePs?si=2IaBVbAYl-l_bn-D',
	},
	{
		id: uuidv4(),
		img: '/public/GamesForAndoid/Pictures/nomb.png',
		imgCard: '/public/GamesForAndoid/PicturesCard/bomb.png',
		subGenre: 'Casual',
		title: 'Bomb Squad',
		downloadLink:
			'https://play.google.com/store/apps/details?id=net.froemling.bombsquad',
		instruction: 'https://bombsquad.fandom.com/wiki/BombSquad_Wiki',
		players: `1 - 8`,
		item: 'itemsBomb',
		descriptionKey: 'subtitleMomb',
		sistemReq: '',
		feedback: '9.0',
		videos: 'https://www.youtube.com/embed/iSQjaWxMwPk?si=W2-5SuZcTPHfkus1',
	},
	{
		id: uuidv4(),
		img: '/public/GamesForAndoid/Pictures/polifyeld.png',
		imgCard: '/public/GamesForAndoid/PicturesCard/polyfield.png',
		subGenre: 'Shooters, Action',
		title: 'Polifyeld',
		downloadLink:
			'https://play.google.com/store/apps/details?id=com.MA.Polyfield&hl=uk',
		instruction: 'https://polyfield.net/',
		players: `1 - 8`,
		item: 'itemsPoli',
		descriptionKey: 'subtitlePoli',
		sistemReq: '',
		feedback: '8.8',
		videos: 'https://www.youtube.com/embed/FKDkJO3ExDQ?si=MRpx8IyJqK972yBQ',
	},
]
